BEGIN;
CREATE TEMP TABLE delete_test_ids AS SELECT gen_random_uuid() actor,gen_random_uuid() target,gen_random_uuid() room,gen_random_uuid() sub,gen_random_uuid() archive;
GRANT SELECT ON delete_test_ids TO authenticated;
INSERT INTO auth.users(id,email) SELECT actor,actor::text||'@example.invalid' FROM delete_test_ids UNION ALL SELECT target,target::text||'@example.invalid' FROM delete_test_ids;
UPDATE public.profiles SET role='admin' WHERE id=(SELECT actor FROM delete_test_ids);
INSERT INTO public.classrooms(id,class_level,room,academic_year,term,created_by) SELECT room,'TEST',actor::text,2569,1,target FROM delete_test_ids;
INSERT INTO public.classroom_teachers(classroom_id,teacher_id) SELECT room,target FROM delete_test_ids;
INSERT INTO public.classroom_submissions(id,classroom_id,report_month,due_date,status,submitted_by) SELECT sub,room,'2026-08-01','2026-09-05','submitted_to_academic',target FROM delete_test_ids;
INSERT INTO public.submission_comments(submission_id,author_id,comment) SELECT sub,target,'preserve test comment' FROM delete_test_ids;
INSERT INTO public.classroom_monthly_archives(id,submission_id,classroom_id,academic_year,term,report_month,due_date,approved_by,approved_name,approved_at,snapshot) SELECT archive,sub,room,2569,1,'2026-08-01','2026-09-05',target,'Preserved signer',now(),'{"test":true}'::jsonb FROM delete_test_ids;
UPDATE public.profiles SET role='admin' WHERE id=(SELECT actor FROM delete_test_ids);
SELECT set_config('request.jwt.claim.sub',(SELECT actor::text FROM delete_test_ids),true);
SET LOCAL ROLE authenticated;
DO $$ DECLARE n integer; BEGIN DELETE FROM public.classroom_monthly_archives WHERE id=(SELECT archive FROM delete_test_ids); GET DIAGNOSTICS n=ROW_COUNT; IF n<>0 THEN RAISE EXCEPTION 'Delete role assertion failed: admin'; END IF; END $$;
RESET ROLE;
UPDATE public.profiles SET role='director' WHERE id=(SELECT actor FROM delete_test_ids);
SELECT set_config('request.jwt.claim.sub',(SELECT actor::text FROM delete_test_ids),true);
SET LOCAL ROLE authenticated;
DO $$ DECLARE n integer; BEGIN DELETE FROM public.classroom_monthly_archives WHERE id=(SELECT archive FROM delete_test_ids); GET DIAGNOSTICS n=ROW_COUNT; IF n<>0 THEN RAISE EXCEPTION 'Delete role assertion failed: director'; END IF; END $$;
RESET ROLE;
UPDATE public.profiles SET role='academic' WHERE id=(SELECT actor FROM delete_test_ids);
SELECT set_config('request.jwt.claim.sub',(SELECT actor::text FROM delete_test_ids),true);
SET LOCAL ROLE authenticated;
DO $$ DECLARE n integer; BEGIN DELETE FROM public.classroom_monthly_archives WHERE id=(SELECT archive FROM delete_test_ids); GET DIAGNOSTICS n=ROW_COUNT; IF n<>0 THEN RAISE EXCEPTION 'Delete role assertion failed: academic'; END IF; END $$;
RESET ROLE;
UPDATE public.profiles SET role='teacher' WHERE id=(SELECT actor FROM delete_test_ids);
SELECT set_config('request.jwt.claim.sub',(SELECT actor::text FROM delete_test_ids),true);
SET LOCAL ROLE authenticated;
DO $$ DECLARE n integer; BEGIN DELETE FROM public.classroom_monthly_archives WHERE id=(SELECT archive FROM delete_test_ids); GET DIAGNOSTICS n=ROW_COUNT; IF n<>0 THEN RAISE EXCEPTION 'Delete role assertion failed: teacher'; END IF; END $$;
RESET ROLE;
UPDATE public.profiles SET role='deputy_director' WHERE id=(SELECT actor FROM delete_test_ids);
SELECT set_config('request.jwt.claim.sub',(SELECT actor::text FROM delete_test_ids),true);
SET LOCAL ROLE authenticated;
DO $$ DECLARE n integer; BEGIN DELETE FROM public.classroom_monthly_archives WHERE id=(SELECT archive FROM delete_test_ids); GET DIAGNOSTICS n=ROW_COUNT; IF n<>1 THEN RAISE EXCEPTION 'Delete role assertion failed: deputy_director'; END IF; END $$;
RESET ROLE;
SELECT set_config('request.jwt.claim.sub','',true);
INSERT INTO public.classroom_monthly_archives(id,submission_id,classroom_id,academic_year,term,report_month,due_date,approved_by,approved_name,approved_at,snapshot) SELECT archive,sub,room,2569,1,'2026-08-01','2026-09-05',target,'Preserved signer',now(),'{"test":true}'::jsonb FROM delete_test_ids;
DELETE FROM auth.users WHERE id=(SELECT target FROM delete_test_ids);
DO $$ BEGIN
IF NOT EXISTS(SELECT 1 FROM public.classroom_monthly_archives WHERE id=(SELECT archive FROM delete_test_ids) AND approved_by IS NULL AND approved_name='Preserved signer' AND snapshot='{"test":true}'::jsonb) THEN RAISE EXCEPTION 'Archive changed'; END IF;
IF NOT EXISTS(SELECT 1 FROM public.classroom_submissions WHERE id=(SELECT sub FROM delete_test_ids) AND submitted_by IS NULL) THEN RAISE EXCEPTION 'Submission lost'; END IF;
IF NOT EXISTS(SELECT 1 FROM public.submission_comments WHERE submission_id=(SELECT sub FROM delete_test_ids) AND author_id IS NULL) THEN RAISE EXCEPTION 'Comment lost'; END IF;
IF EXISTS(SELECT 1 FROM public.profiles WHERE id=(SELECT target FROM delete_test_ids)) OR EXISTS(SELECT 1 FROM public.classroom_teachers WHERE teacher_id=(SELECT target FROM delete_test_ids)) THEN RAISE EXCEPTION 'Account membership remains'; END IF;
END $$;
ROLLBACK;
SELECT 'PASS: deputy-only archive deletion; account deletion preserves room, submission, snapshot, signer and comments; all fixtures rolled back' result;