BEGIN;
CREATE TEMP TABLE delete_test_ids AS SELECT gen_random_uuid() actor,gen_random_uuid() target,gen_random_uuid() room,gen_random_uuid() sub,gen_random_uuid() archive;
GRANT SELECT ON delete_test_ids TO authenticated;
INSERT INTO auth.users(id,email) SELECT actor,actor::text||'@example.invalid' FROM delete_test_ids UNION ALL SELECT target,target::text||'@example.invalid' FROM delete_test_ids;
UPDATE public.profiles SET role='admin' WHERE id=(SELECT actor FROM delete_test_ids);
INSERT INTO public.classrooms(id,class_level,room,academic_year,term,created_by) SELECT room,'TEST',actor::text,2569,1,target FROM delete_test_ids;
INSERT INTO public.classroom_teachers(classroom_id,teacher_id) SELECT room,target FROM delete_test_ids;
INSERT INTO public.classroom_submissions(id,classroom_id,report_month,due_date,status,submitted_by) SELECT sub,room,'2026-08-01','2026-09-05','submitted_to_academic',target FROM delete_test_ids;
INSERT INTO public.submission_comments(submission_id,author_id,comment) SELECT sub,target,'preserve test comment' FROM delete_test_ids;
INSERT INTO public.classroom_monthly_archives(id,submission_id,classroom_id,academic_year,term,report_month,due_date,approved_by,approved_name,approved_at,snapshot) SELECT archive,sub,room,2569,1,'2026-08-01','2026-09-05',target,'Preserved signer',now(),'{"test":true}'::jsonb FROM delete_test_ids;
INSERT INTO public.classroom_submissions(classroom_id,report_month,due_date,status) SELECT room,'2026-07-01','2026-08-05','submitted_to_academic' FROM delete_test_ids;
INSERT INTO public.module_data(classroom_id,module_name,data) SELECT room,'report_checks','{"2026-08":{"savings_none":true}}'::jsonb FROM delete_test_ids;
UPDATE public.profiles SET role='admin' WHERE id=(SELECT actor FROM delete_test_ids);
SELECT set_config('request.jwt.claim.sub',(SELECT actor::text FROM delete_test_ids),true);
SET LOCAL ROLE authenticated;
DO $$ DECLARE n integer; BEGIN DELETE FROM public.classroom_monthly_archives WHERE id=(SELECT archive FROM delete_test_ids); GET DIAGNOSTICS n=ROW_COUNT; IF n<>0 THEN RAISE EXCEPTION 'Role test failed: admin'; END IF; END $$;
RESET ROLE;
DO $$ BEGIN IF (SELECT count(*) FROM public.classroom_submissions WHERE id=(SELECT sub FROM delete_test_ids))<>1 THEN RAISE EXCEPTION 'Submission cleanup failed: admin'; END IF; END $$;
UPDATE public.profiles SET role='director' WHERE id=(SELECT actor FROM delete_test_ids);
SELECT set_config('request.jwt.claim.sub',(SELECT actor::text FROM delete_test_ids),true);
SET LOCAL ROLE authenticated;
DO $$ DECLARE n integer; BEGIN DELETE FROM public.classroom_monthly_archives WHERE id=(SELECT archive FROM delete_test_ids); GET DIAGNOSTICS n=ROW_COUNT; IF n<>0 THEN RAISE EXCEPTION 'Role test failed: director'; END IF; END $$;
RESET ROLE;
DO $$ BEGIN IF (SELECT count(*) FROM public.classroom_submissions WHERE id=(SELECT sub FROM delete_test_ids))<>1 THEN RAISE EXCEPTION 'Submission cleanup failed: director'; END IF; END $$;
UPDATE public.profiles SET role='academic' WHERE id=(SELECT actor FROM delete_test_ids);
SELECT set_config('request.jwt.claim.sub',(SELECT actor::text FROM delete_test_ids),true);
SET LOCAL ROLE authenticated;
DO $$ DECLARE n integer; BEGIN DELETE FROM public.classroom_monthly_archives WHERE id=(SELECT archive FROM delete_test_ids); GET DIAGNOSTICS n=ROW_COUNT; IF n<>0 THEN RAISE EXCEPTION 'Role test failed: academic'; END IF; END $$;
RESET ROLE;
DO $$ BEGIN IF (SELECT count(*) FROM public.classroom_submissions WHERE id=(SELECT sub FROM delete_test_ids))<>1 THEN RAISE EXCEPTION 'Submission cleanup failed: academic'; END IF; END $$;
UPDATE public.profiles SET role='teacher' WHERE id=(SELECT actor FROM delete_test_ids);
SELECT set_config('request.jwt.claim.sub',(SELECT actor::text FROM delete_test_ids),true);
SET LOCAL ROLE authenticated;
DO $$ DECLARE n integer; BEGIN DELETE FROM public.classroom_monthly_archives WHERE id=(SELECT archive FROM delete_test_ids); GET DIAGNOSTICS n=ROW_COUNT; IF n<>0 THEN RAISE EXCEPTION 'Role test failed: teacher'; END IF; END $$;
RESET ROLE;
DO $$ BEGIN IF (SELECT count(*) FROM public.classroom_submissions WHERE id=(SELECT sub FROM delete_test_ids))<>1 THEN RAISE EXCEPTION 'Submission cleanup failed: teacher'; END IF; END $$;
UPDATE public.profiles SET role='deputy_director' WHERE id=(SELECT actor FROM delete_test_ids);
SELECT set_config('request.jwt.claim.sub',(SELECT actor::text FROM delete_test_ids),true);
SET LOCAL ROLE authenticated;
DO $$ DECLARE n integer; BEGIN DELETE FROM public.classroom_monthly_archives WHERE id=(SELECT archive FROM delete_test_ids); GET DIAGNOSTICS n=ROW_COUNT; IF n<>1 THEN RAISE EXCEPTION 'Role test failed: deputy_director'; END IF; END $$;
RESET ROLE;
DO $$ BEGIN IF (SELECT count(*) FROM public.classroom_submissions WHERE id=(SELECT sub FROM delete_test_ids))<>0 THEN RAISE EXCEPTION 'Submission cleanup failed: deputy_director'; END IF; END $$;
DO $$ BEGIN
IF EXISTS(SELECT 1 FROM public.submission_comments WHERE submission_id=(SELECT sub FROM delete_test_ids)) THEN RAISE EXCEPTION 'Old review comments remain'; END IF;
IF NOT EXISTS(SELECT 1 FROM public.classroom_submissions WHERE classroom_id=(SELECT room FROM delete_test_ids) AND report_month='2026-07-01') THEN RAISE EXCEPTION 'Other month changed'; END IF;
IF NOT EXISTS(SELECT 1 FROM public.module_data WHERE classroom_id=(SELECT room FROM delete_test_ids) AND data='{"2026-08":{"savings_none":true}}'::jsonb) THEN RAISE EXCEPTION 'Teacher data changed'; END IF;
IF NOT EXISTS(SELECT 1 FROM public.classroom_teachers WHERE classroom_id=(SELECT room FROM delete_test_ids)) THEN RAISE EXCEPTION 'Assignment changed'; END IF;
END $$;
ROLLBACK;
SELECT 'PASS: deputy-only atomic archive and submission deletion; old review removed; teacher data, assignment and other month preserved; fixtures rolled back' result;