-- Central school data: retain existing classrooms, profiles and student identities.
alter table public.school_signatories add column school_name text, add column office_name text, add column address text, add column academic_head text, add column deputy_name text, add column assessment_name text;
update public.school_signatories set school_name=(select case when count(distinct school_name)=1 then min(school_name) end from public.classrooms), office_name=(select case when count(distinct office_name)=1 then min(office_name) end from public.classrooms), academic_head=(select case when count(distinct academic_head)=1 then min(academic_head) end from public.classrooms), deputy_name=(select case when count(distinct deputy)=1 then min(deputy) end from public.classrooms) where id=1;
alter table public.classrooms add column teacher1_id uuid references public.profiles(id) on delete set null, add column teacher2_id uuid references public.profiles(id) on delete set null;
create index classrooms_teacher1_id_idx on public.classrooms(teacher1_id);
create index classrooms_teacher2_id_idx on public.classrooms(teacher2_id);
create table public.subject_catalog(id uuid primary key default gen_random_uuid(),code text not null unique check(length(btrim(code)) between 1 and 40),name text not null check(length(btrim(name)) between 1 and 110),department integer not null check(department between 0 and 7),credits numeric not null default 1 check(credits>=0 and credits<=20),weekly_hours numeric not null default 1 check(weekly_hours>=0 and weekly_hours<=40),active boolean not null default true,revision integer not null default 1,updated_at timestamptz not null default now());
alter table public.subject_catalog enable row level security;
revoke all on public.subject_catalog from anon,authenticated;
grant select,insert,update on public.subject_catalog to authenticated;
create policy subjects_read on public.subject_catalog for select to authenticated using(true);
create policy subjects_insert on public.subject_catalog for insert to authenticated with check((select private.is_management()));
create policy subjects_update on public.subject_catalog for update to authenticated using((select private.is_management())) with check((select private.is_management()));
create table public.teaching_assignments(id uuid primary key default gen_random_uuid(),classroom_id uuid not null references public.classrooms(id),subject_id uuid not null references public.subject_catalog(id),teacher_id uuid not null references public.profiles(id),teacher_name text not null default '',active boolean not null default true,revision integer not null default 1,updated_at timestamptz not null default now(),unique(classroom_id,subject_id,teacher_id));
create index teaching_assignments_subject_idx on public.teaching_assignments(subject_id);
create index teaching_assignments_teacher_idx on public.teaching_assignments(teacher_id);
alter table public.teaching_assignments enable row level security;
revoke all on public.teaching_assignments from anon,authenticated;
grant select,insert,update on public.teaching_assignments to authenticated;
create policy teaching_read on public.teaching_assignments for select to authenticated using(private.can_view_classroom(classroom_id));
create policy teaching_insert on public.teaching_assignments for insert to authenticated with check((select private.is_management()));
create policy teaching_update on public.teaching_assignments for update to authenticated using((select private.is_management())) with check((select private.is_management()));
alter table public.pp5_books add column assignment_id uuid references public.teaching_assignments(id);
create unique index pp5_books_assignment_idx on public.pp5_books(assignment_id) where assignment_id is not null;
create function private.central_room_defaults() returns trigger language plpgsql security invoker set search_path='' as $$ declare s public.school_signatories%rowtype; begin select * into s from public.school_signatories where id=1; new.school_name=coalesce(s.school_name,new.school_name);new.office_name=coalesce(s.office_name,new.office_name);new.academic_head=coalesce(s.academic_head,new.academic_head);new.deputy=coalesce(s.deputy_name,new.deputy);if new.teacher1_id is not null then new.teacher1=coalesce((select display_name from public.profiles where id=new.teacher1_id),new.teacher1);end if;if new.teacher2_id is not null then new.teacher2=coalesce((select display_name from public.profiles where id=new.teacher2_id),new.teacher2);end if;return new;end $$;
create trigger central_room_defaults before insert or update on public.classrooms for each row execute function private.central_room_defaults();
create function private.central_school_sync() returns trigger language plpgsql security invoker set search_path='' as $$ begin if (new.school_name,new.office_name,new.academic_head,new.deputy_name) is distinct from (old.school_name,old.office_name,old.academic_head,old.deputy_name) then update public.classrooms set school_name=coalesce(new.school_name,school_name),office_name=coalesce(new.office_name,office_name),academic_head=coalesce(new.academic_head,academic_head),deputy=coalesce(new.deputy_name,deputy);end if;return new;end $$;
create trigger central_school_sync after update on public.school_signatories for each row execute function private.central_school_sync();
create function private.central_assignment_defaults() returns trigger language plpgsql security invoker set search_path='' as $$ begin if tg_op='UPDATE' and (new.classroom_id,new.subject_id,new.teacher_id) is distinct from (old.classroom_id,old.subject_id,old.teacher_id) then raise exception 'Create a new assignment instead of moving an existing assignment';end if;select display_name into new.teacher_name from public.profiles where id=new.teacher_id; if new.teacher_name is null then raise exception 'Teacher profile not found';end if;if new.active and (tg_op='INSERT' or old.active=false) then insert into public.classroom_teachers(classroom_id,teacher_id,permission) values(new.classroom_id,new.teacher_id,'editor') on conflict(classroom_id,teacher_id) do update set permission=case when public.classroom_teachers.permission='owner' then 'owner' else 'editor' end;end if;return new;end $$;
create trigger central_assignment_defaults before insert or update on public.teaching_assignments for each row execute function private.central_assignment_defaults();
create function private.central_profile_sync() returns trigger language plpgsql security invoker set search_path='' as $$ begin if new.display_name is distinct from old.display_name then update public.classrooms set teacher1=new.display_name where teacher1_id=new.id;update public.classrooms set teacher2=new.display_name where teacher2_id=new.id;update public.teaching_assignments set teacher_name=new.display_name,revision=revision+1,updated_at=now() where teacher_id=new.id;end if;return new;end $$;
create trigger central_profile_sync after update of display_name on public.profiles for each row execute function private.central_profile_sync();
create function private.central_book_assignment() returns trigger language plpgsql security invoker set search_path='' as $$ begin if new.assignment_id is not null and not exists(select 1 from public.teaching_assignments a where a.id=new.assignment_id and a.classroom_id=new.classroom_id) then raise exception 'Assignment does not belong to this classroom';end if;return new;end $$;
create trigger central_book_assignment before insert or update of assignment_id,classroom_id on public.pp5_books for each row execute function private.central_book_assignment();
revoke all on function private.central_room_defaults(),private.central_school_sync(),private.central_assignment_defaults(),private.central_profile_sync(),private.central_book_assignment() from public,anon,authenticated;

create unique index students_classroom_code_idx on public.students(classroom_id,student_code) where btrim(student_code)<>'';

